# Generated by Django 4.1.4 on 2023-11-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
